version: '3.8'

services:
  vm-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
      - DATABASE_URL=postgresql://vm_user:vm_password@postgres:5432/vm_service
    volumes:
      - ../src:/app/src
      - ../server.py:/app/server.py
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=vm_service
      - POSTGRES_USER=vm_user
      - POSTGRES_PASSWORD=vm_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: